name: Build
on:
  - push

env:
  IMAGE_NAME: prometheus-solar-exporter

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image for amd64
        run: docker build -t image:amd64 .

      - name: Build image for arm32v7
        run: docker build -t image:arm32v7 --build-arg RUNTIME=3.1-buster-slim-arm32v7 --build-arg PUBLISH_RID=linux-arm  .

      - name: Build image for arm64v8
        run: docker build -t image:arm64v8 --build-arg RUNTIME=3.1-buster-slim-arm64v8 --build-arg PUBLISH_RID=linux-arm  .

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push images
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          BRANCH_OR_TAG=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$BRANCH_OR_TAG" == "master" ] && BRANCH_OR_TAG=latest

          # Print variables
          echo IMAGE_ID=$IMAGE_ID
          echo BRANCH_OR_TAG=$BRANCH_OR_TAG

          # Tag images
          docker tag image:amd64 $IMAGE_ID:$BRANCH_OR_TAG-amd64
          docker tag image:arm32v7 $IMAGE_ID:$BRANCH_OR_TAG-arm32v7
          docker tag image:arm64v8 $IMAGE_ID:$BRANCH_OR_TAG-arm64v8

          # Push images
          docker push $IMAGE_ID:$BRANCH_OR_TAG-amd64
          docker push $IMAGE_ID:$BRANCH_OR_TAG-arm32v7
          docker push $IMAGE_ID:$BRANCH_OR_TAG-arm64v8

          # Create manifest list
          docker manifest create $IMAGE_ID:$BRANCH_OR_TAG $IMAGE_ID:$BRANCH_OR_TAG-amd64 $IMAGE_ID:$BRANCH_OR_TAG-arm32v7 $IMAGE_ID:$BRANCH_OR_TAG-arm64v8
          docker manifest annotate --arch amd64 $IMAGE_ID:$BRANCH_OR_TAG $IMAGE_ID:$BRANCH_OR_TAG-amd64
          docker manifest annotate --arch armv7 $IMAGE_ID:$BRANCH_OR_TAG $IMAGE_ID:$BRANCH_OR_TAG-arm32v7
          docker manifest annotate --arch arm64 $IMAGE_ID:$BRANCH_OR_TAG $IMAGE_ID:$BRANCH_OR_TAG-arm64v8

          # Push manifest list
          docker manifest push $IMAGE_ID:$BRANCH_OR_TAG
